# SPDX-License-Identifier: Apache-2.0
# Keep GitHub Actions pins current; one grouped PR a month. NuGet version
# bumps stay manual (security updates are enabled repo-side instead).
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
